version: '2.3'

services:
  ci:
    container_name: $SRV
    build:
      context: .
      dockerfile: deploy/ci.dockerfile
    image: $REG/ci/$SRV:$CI
    volumes:
      - ./src:/srv
    env_file: data.env
  rt:
    container_name: $SRV
    build:
      context: .
      args:
        CI: $REG/ci/$SRV:$CI
    shm_size: 1024MB
    volumes:
      - /home/huramba/datasets/test-syringe.2021-06-17-11-50/:/srv/dataset
    env_file: data.env
    image: $REG/rt/$SRV:$RT
    restart: always